### ISSUE TITLE
Getting Crash on Release Build 

### ISSUE THREAD

**Issue by mohitmanuja** [cashfree/cashfree-android-sdk-v0#45]
java.lang.IllegalArgumentException: No enum constant com.gocashfree.cashfreesdk.d.a.a.f
        at java.lang.Enum.valueOf(Enum.java:258)
        at com.gocashfree.cashfreesdk.d.a$a.valueOf(:1)
        at com.gocashfree.cashfreesdk.c.a.c(:2)
        at com.gocashfree.cashfreesdk.c.b.h(:2)
        at com.gocashfree.cashfreesdk.c.b$b.a(:3)
        at com.gocashfree.cashfreesdk.a.c.b.b$a.a(:2)
        at com.gocashfree.cashfreesdk.a.c.b.b$a.onResponse(:1)
        at com.android.volley.toolbox.StringRequest.deliverResponse(StringRequest.java:5)
        at com.android.volley.toolbox.StringRequest.deliverResponse(StringRequest.java:1)
        at com.android.volley.ExecutorDelivery$ResponseDeliveryRunnable.run(ExecutorDelivery.java:4)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6898)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:537)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)

**Comment by mohitmanuja** [comment]
I am using proguard with minified true .

**Comment by mohitmanuja** [comment]
@arjun-cashfree @tushar-cashfree Please look into this asap.

**Comment by arjun-cashfree** [comment]
Please reach out to techsupport@cashfree.com for any help with the integration.
