### ISSUE TITLE
in 5.0 Android Version its crashing

### ISSUE THREAD

**Issue by JagadishaIncture** [cashfree/cashfree-android-sdk-v0#50]
Fatal Exception: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.mipl.munchesta/com.gocashfree.cashfreesdk.ui.web_checkout.CFPaymentActivity}: android.view.InflateException: Binary XML file line #26: Error inflating class com.gocashfree.cashfreesdk.ui.web_checkout.CFWebView
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2298)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2360)
       at android.app.ActivityThread.access$800(ActivityThread.java:144)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1278)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:135)
       at android.app.ActivityThread.main(ActivityThread.java:5232)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:898)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:693)

**Comment by arjun-cashfree** [comment]
This crash is because of the older version of the Appcompat library used in your project. Please update it to the latest version (1.2.0+) and that should solve it.  

https://issuetracker.google.com/issues/141132133

**Comment by anizmo** [comment]
Hi @arjun-cashfree, can you upload a better version of the sample app which has all the payment modes integrated?

**Comment by arjun-cashfree** [comment]
I've added the sample code for seamless modes. Let us know if you need anything else.
