### ISSUE TITLE
crash when transaction is cancelled with prod configs

### ISSUE THREAD

**Issue by shrastiRisor** [cashfree/cashfree-android-sdk-v0#68]
Process: com.risor, PID: 16346
    java.lang.IllegalStateException: FragmentManager has been destroyed
        at androidx.fragment.app.FragmentManager.enqueueAction(FragmentManager.java:1878)
        at androidx.fragment.app.BackStackRecord.commitInternal(BackStackRecord.java:329)
        at androidx.fragment.app.BackStackRecord.commit(BackStackRecord.java:294)
        at com.cashfree.pg.ui.web_checkout.CFPaymentActivity$h$a.run(Unknown Source:183)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:223)
        at android.app.ActivityThread.main(ActivityThread.java:7562)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)

**Comment by arjun-cashfree** [comment]
Our SDK does not use fragments. Please provide more information like steps to reproduce, OS version, Device info etc.

**Comment by shrastiRisor** [comment]
@arjun-cashfree It is happening only on PROD flavor and seamless checkout for all OS versions. Steps:
1. initiate flow by passing appropriate params.
2. cancel the transaction by pressing backpress or cancel on toolbar.
3. Leads to crash and it somehow hangs the main thread

**Comment by arjun-cashfree** [comment]
Please add the full error logs.

**Comment by shrastiRisor** [comment]
I am able to reproduce it on sample app as well.  In CFPaymentActivity.class, at line 348, there is delay before committing transaction. If somebody cancels the flow within that period, app hangs. 

App's log

2022-03-23 13:25:58.862 28912-28912/com.gocashfree.cfsdk.sample.cfsdksample E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.gocashfree.cfsdk.sample.cfsdksample, PID: 28912
    java.lang.IllegalStateException: Can not perform this action after onSaveInstanceState
        at androidx.fragment.app.FragmentManagerImpl.checkStateLoss(FragmentManagerImpl.java:1536)
        at androidx.fragment.app.FragmentManagerImpl.enqueueAction(FragmentManagerImpl.java:1558)
        at androidx.fragment.app.BackStackRecord.commitInternal(BackStackRecord.java:317)
        at androidx.fragment.app.BackStackRecord.commit(BackStackRecord.java:282)
        at com.cashfree.pg.ui.web_checkout.CFPaymentActivity$b$a.run(SourceFile:28)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6669)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)


FragmentManager's log: 

03-23 13:10:41.857 27315 27315 V FragmentManager: Commit: BackStackEntry{9ddac2f}
03-23 13:10:41.858 27315 27315 D FragmentManager:   mName=null mIndex=-1 mCommitted=false
03-23 13:10:41.858 27315 27315 D FragmentManager:   mTransition=#1001  Operations:
03-23 13:10:41.859 27315 27315 D FragmentManager:     Op #0: ADD CustomerIDFragment{932d23c} (5ec1dd37-a9ad-483c-8568-a9d4cb1ed8b1 id=0x7f0a018e tag=OtpFragment)
03-23 13:10:41.862 27315 27315 E AndroidRuntime: java.lang.IllegalStateException: FragmentManager has been destroyed
03-23 13:10:41.862 27315 27315 E AndroidRuntime: 	at androidx.fragment.app.FragmentManager.enqueueAction(FragmentManager.java:1878)

Please let me know if you need any other information.

**Comment by shrastiRisor** [comment]
@arjun-cashfree do you need any other information as this is very frequent while cancelling the payments

**Comment by arjun-cashfree** [comment]
Please update the SDK to the latest version 1.7.19.

**Comment by shrastiRisor** [comment]
@arjun-cashfree  Seems like com.cashfree.pg:android-sdk:1.7.19 is not available. Could you please confirm the version. Also, where can I see the latest releases in such cases?

**Comment by arjun-cashfree** [comment]
v1.7.20 is the latest version. Apologies for the confusion.

**Comment by shrastiRisor** [comment]
@arjun-cashfree  Thank you. I am not able to reproduce issue anymore.
